### ISSUE TITLE
load only active menu elements

### ISSUE THREAD

**Issue by AlexMSG** [maxsv0/sitograph#193]
msv_load_pagemenu()
$result = db_get_list(TABLE_MENU, "`", "`order_id` asc");
replace 
$result = db_get_list(TABLE_MENU, "`published` = 1", "`order_id` asc");

**Comment by maxsv0** [comment]
already fixed
https://github.com/maxsv0/sitograph/blob/master/src/include/module/msv-api/msv-api.functions.php
