### ISSUE TITLE
Load pdf file bug

### ISSUE THREAD

**Issue by AlexMSG** [maxsv0/sitograph#47]
при попытке загрузить тут https://gyazo.com/91abb80addfd17a059707c53674d03a5
выдает https://gyazo.com/7f55c4bd477d6da131ed0a48b68f2ae9

**Comment by maxsv0** [comment]
Загрузка не удается, потому что Медиа библиотека блокирует загрузку всех файлов кроме:
  IMAGETYPE_PNG => "png",
  IMAGETYPE_JPEG => "jpg",
  IMAGETYPE_GIF => "gif"

**Comment by maxsv0** [comment]
fixed in dev
