### ISSUE TITLE
Структура сайта -> Save & Save Exit bug

### ISSUE THREAD

**Issue by AlexMSG** [maxsv0/sitograph#49]
не сохраняются изменения в структуре сайта http://newmcg.sudo.com.ua
в частности - селектор Родительский ID

**Comment by maxsv0** [comment]
Проблема в конвертации parent_url=>parent_id

**Comment by maxsv0** [comment]
На данный момент лучшее решение - переработать модуль core, чтобы изменить таблицу structure и поменять числовой parent_id на строковой parent_url.
